DROP TABLE IF EXISTS PERSONS;
DROP TABLE IF EXISTS AUTHORS;
DROP TABLE IF EXISTS BOOKS;
DROP TABLE IF EXISTS GENRES;
CREATE TABLE AUTHORS(ID BIGINT PRIMARY KEY, NAME VARCHAR(255));
CREATE TABLE GENRES(ID BIGINT PRIMARY KEY, NAME VARCHAR(255));
CREATE TABLE BOOKS(ID BIGINT PRIMARY KEY, NAME VARCHAR(255), AUTHOR_ID BIGINT, GENRE_ID BIGINT,
                   foreign key (AUTHOR_ID) references AUTHORS(ID),
                   foreign key (GENRE_ID) references GENRES(ID))

