DROP TABLE IF EXISTS BOOKS;
DROP TABLE IF EXISTS GENRES;
DROP TABLE IF EXISTS AUTHORS;
CREATE TABLE AUTHORS
(
    ID   BIGINT PRIMARY KEY,
    NAME VARCHAR(255)
);
CREATE TABLE GENRES
(
    ID   BIGINT PRIMARY KEY,
    NAME VARCHAR(255)
);
CREATE TABLE BOOKS
(
    ID        BIGINT PRIMARY KEY,
    NAME      VARCHAR(255),
    AUTHOR_ID BIGINT,
    GENRE_ID  BIGINT,
    foreign key (AUTHOR_ID) references AUTHORS (ID) ON DELETE CASCADE ON UPDATE CASCADE,
    foreign key (GENRE_ID) references GENRES (ID) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE COMMENTS
(
    ID        BIGINT PRIMARY KEY,
    COMMENT_TEXT      VARCHAR(255),
    BOOK_ID BIGINT references BOOKS(ID) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE SEQUENCE "GENRE_ID_SEQUENCE"
    MINVALUE 1
    MAXVALUE 999999999
    INCREMENT BY 1
    START WITH 6;

CREATE SEQUENCE "AUTHOR_ID_SEQUENCE"
    MINVALUE 1
    MAXVALUE 999999999
    INCREMENT BY 1
    START WITH 4;

CREATE SEQUENCE "BOOK_ID_SEQUENCE"
    MINVALUE 1
    MAXVALUE 999999999
    INCREMENT BY 1
    START WITH 8;

CREATE SEQUENCE "COMMENT_ID_SEQUENCE"
    MINVALUE 1
    MAXVALUE 999999999
    INCREMENT BY 1
    START WITH 3;