spring:
  messages:
    basename: "i18n/appmessages"
    encoding: "UTF-8"
  shell:
    interactive:
      enabled: true
questions:
  resource:
    file :
      mask: "questions_*.csv"
  min:
    score: 5

application:
  locale: ru_RU
